Added two factor setup.
userwidgets/ui pull request #117
Opened 2024-02-06 12:50 UTC by marcushanses

- [x] https://github.com/userwidgets/model/pull/71
- [x] https://github.com/utily/cryptly/pull/59

2024-02-06 12:56 UTC, marcushanses commented
![bild](https://github.com/userwidgets/ui/assets/79835961/581496aa-05d1-4f7b-a608-1dad6f8dd478)

2024-02-06 13:16 UTC, AntonCroner requested changes

2024-02-06 13:16 UTC, AntonCroner commented on src/components/me/two-factor/translation/index.tsx
either write translations or remove

2024-02-06 13:16 UTC, AntonCroner commented on src/components/me/two-factor/index.tsx
> +			<smoothly-summary>
idk if the summary should be built into the 2fa component. Maybe someone else wants to have it under something else? idk tho

2024-02-07 08:49 UTC, marcushanses commented
![bild](https://github.com/userwidgets/ui/assets/79835961/59a4818c-5f25-4203-b8cb-9dcbc2087ba2)

2024-02-07 09:01 UTC, AntonCroner approved these changes

2024-02-07 09:11 UTC, merged