lazy loading and storing org
userwidgets/ui pull request #122
Opened 2024-02-13 15:39 UTC by EliasEriksson

* using lazy subscriptions internally in state
* saving current organization id in sessionstorage that is used to try to get determine the current organization on page load

2024-02-13 15:43 UTC, AntonCroner requested changes

2024-02-13 15:43 UTC, AntonCroner commented on src/State/Organizations.ts
> +				if (index != -1)
there are waaay too many nested if statements

2024-02-13 15:50 UTC, EliasEriksson reviewed
self check

2024-02-14 09:04 UTC, AntonCroner approved these changes

2024-02-14 09:05 UTC, merged