Status heading in user table. Only displays if user has 2fa enabled s…
userwidgets/ui pull request #124
Opened 2024-02-19 16:18 UTC by AntonCroner

…o far.

2024-02-19 16:32 UTC, EliasEriksson requested changes

2024-02-19 16:32 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +		const statuses: string[] = []
instead of defining variables in the render function its preferable to define a `@State()` with the array and one `@Watch("...")`er for each of its dependencies. this way that array is not redefined every time the component renders and is kept up to date if the user of the component suddenly redefines what the user property is.
```ts
@State() statuses: string[] = []
@Watch("user")
userChagned(): void {
    const statuses: string[] = []
    if (this.user.twoFactor)
        statuses.push("2fa")
}
```

2024-02-19 16:32 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +							const label = labels.find(l => l.name == s) ?? { name: s, description: "", hue: 360 }
maybe use a record over an array? then we can skip the find

2024-02-20 08:30 UTC, AntonCroner commented on src/components/user/list/row/index.tsx
> +							const label = labels.find(l => l.name == s) ?? { name: s, description: "", hue: 360 }
\+

2024-02-20 08:34 UTC, AntonCroner commented on src/components/user/list/row/index.tsx
> +		const statuses: string[] = []
Does it really need State? what i wrote just now not enough?

2024-02-20 08:40 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +		const statuses: string[] = []
I mean no that works too. but now you still do a job that might be unnecessary every render. so functionally its the same.

2024-02-20 08:43 UTC, EliasEriksson requested changes

2024-02-20 08:43 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +	statuses: string[] = []
is there a reason we do not build an array of labels directly so we can skip the `const` + `return` in the map in `render()`?

2024-02-20 08:48 UTC, AntonCroner commented on src/components/user/list/row/index.tsx
> +	statuses: string[] = []
\+

2024-02-20 09:14 UTC, EliasEriksson approved these changes
Beautiful :tada:

2024-02-20 09:28 UTC, merged