Added status label for displaying last password change.
userwidgets/ui pull request #132
Opened 2024-03-20 19:29 UTC by AntonCroner

2024-03-21 08:19 UTC, EliasEriksson requested changes

2024-03-21 08:19 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +								{s.icon && <smoothly-icon name={s.icon as any}></smoothly-icon>}
we can eliminate this any cast if we make a minor update to smoothly. apparently the export for this type is missing in the smoothly repos `src/smoothly.ts` file. do you mind making a small smoothly PR exposing this type so we can type the interface for this properly?

2024-03-21 08:42 UTC, AntonCroner commented on src/components/user/list/row/index.tsx
> +								{s.icon && <smoothly-icon name={s.icon as any}></smoothly-icon>}
It is exported, but it doesn't work. I remember because i tried it before :upside_down_face:

2024-03-25 13:34 UTC, EliasEriksson commented on src/components/user/list/row/index.tsx
> +								{s.icon && <smoothly-icon name={s.icon as any}></smoothly-icon>}
for me it seams to be missing tho? 
```ts
export { Components, JSX } from "./components"
export {
	Autocomplete,
	ClientIdentifier,
	Color,
	Fill,
	GoogleFont,
	Message,
	Notice,
	Trigger,
	Option,
	Listenable,
	HasListenable,
	WithListenable,
	CanBeListenable,
	StateBase,
	Data,
	redirect,
} from "./model"
export { Cosmetic } from "./utilities"
```

2024-03-25 14:05 UTC, EliasEriksson approved these changes

2024-03-25 14:05 UTC, merged