Registration work
userwidgets/ui pull request #20
Opened 2022-09-06 14:37 UTC by linusarnejohansson

2022-09-06 15:24 UTC, EliasEriksson requested changes
minor things

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/login/index.tsx
> +			state.options = { user: response.email, applicationId: response.audience }
this is done inside `this.state.me.login()` already. unnecessary to also do it here.

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/index.tsx
> +		console.log("handleClick")
remove console.log

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/style.css
> +	right: auto ;
this is unnecessary now when we use transform.

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/style.css
> +	color: black;
is this color a leftover for something or intentional?

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/style.css
> +.menu > * {
double selector on `.menu`

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/style.css
> +	padding: 1rem;
this value overwrites the padding from the other `.menu` selector. take one or the other not both at the same time.

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/menu/style.css
> +	background-color: rgba(255, 255, 255, 0.55);
can we use a smoothly color instead? if not, ignore this.

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> +		console.log("state.options", state.options)
remove these console logs

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> +		console.log("organization picker componentWillLoad")
remove console logs

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> +		console.log("handleMenuClose state", state.options.organizationId)
remove console log

2022-09-06 15:24 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> +				<p>You are not a member of any organization.</p>
can we use something else than a p tag for this? if not ignore this.

2022-09-06 15:27 UTC, EliasEriksson commented
Currently the component only shows IDs. It should also fetch the organizations and use their names for display. Using IDs in both places was a starting point. Ask me when you get to this point,

2022-09-07 06:20 UTC, linusarnejohansson commented on src/components/menu/style.css
> +	right: auto ;
position absolute is necessary so is keeping that rule. top and right appears to be unnecessary so will remove those

2022-09-07 11:05 UTC, EliasEriksson requested changes

2022-09-07 11:05 UTC, EliasEriksson commented on src/State/Users.ts
> +	constructor(listenable: Users & Listenable<Users>, client: Client) {
make the constructor private

2022-09-07 11:05 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> +// now use the new state application to fetch names
remove comment

2022-09-07 11:05 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
>  	handelKey() {
change name to `handleAppliicationChange`, or `applicationChanged` or similar

2022-09-07 11:05 UTC, EliasEriksson commented on src/components/organizationPicker/index.tsx
> -		event.stopPropagation()
bring this back. it should not propagate higher in the DOM.

2022-09-07 11:13 UTC, merged