User listing
userwidgets/ui pull request #84
Opened 2023-09-28 12:48 UTC by EliasEriksson

Heavy modifications to old previous user listing components. 
* implemented user table
* implemented invited user table

These tables are not fully featured. They are still missing addition/modification of permissions. These changes makes it possible to invite (default permissions), re-invite (default permissions) and remove users from and organization.

2023-09-28 13:03 UTC, EliasEriksson reviewed
self check

2023-09-28 13:03 UTC, EliasEriksson commented on src/components/user/list/invite/cell/style.css
> +:host::slotted(smoothly-table-expandable-cell > aside > smoothly-icon) {
move to bottom

2023-10-02 06:39 UTC, EliasEriksson commented on src/components/login/index.tsx
> -		if (userwidgets.User.Key.is(response) && this.resolves) {
remove and solve in another PR

2023-10-02 06:55 UTC, EliasEriksson reviewed
self check

2023-10-02 07:01 UTC, EliasEriksson commented
# screenshots
## user table
![image](https://github.com/userwidgets/ui/assets/25643315/0c88759a-0146-4fb0-939b-dd8682f34af2)
![image](https://github.com/userwidgets/ui/assets/25643315/c6ae97b6-8a7f-4abf-8263-52a0eb61c12f)
![image](https://github.com/userwidgets/ui/assets/25643315/fd791331-61d2-47ef-8abd-1e5931fb11b4)

## user invite table
![image](https://github.com/userwidgets/ui/assets/25643315/07ea0aa7-00fc-4eea-b645-b7e5f59eb7ec)

![image](https://github.com/userwidgets/ui/assets/25643315/55f12408-0e3b-4b6e-980d-f2ca442b43b2)
![image](https://github.com/userwidgets/ui/assets/25643315/cfc85646-f68a-48d0-b206-6b14df9d110b)

2023-10-02 07:44 UTC, TheLillyleaf commented on src/State/Users.ts
> +			const users = this.#value
Why make the variable? 

When accesing it this.#value we are not calling the getter, right?

2023-10-02 07:44 UTC, TheLillyleaf commented on src/components/user/invited/index.tsx
> +	async invite() {
Since it's re-inviting, maybe the function should have that name?

2023-10-02 07:44 UTC, TheLillyleaf commented on src/components/user/invited/list/row/translation/index.ts
> +import { sv } from "./sv"
new imports

2023-10-02 07:44 UTC, TheLillyleaf commented on src/components/user/invited/list/translation/index.ts
> +import { sv } from "./sv"
new imports

2023-10-02 07:44 UTC, TheLillyleaf commented on src/components/user/invited/translation/index.ts
> +import { sv } from "./sv"
new imports

2023-10-02 07:44 UTC, TheLillyleaf commented on src/components/user/list/index.tsx
> +	@Prop({ mutable: true }) organization?: userwidgets.Organization | null = null
Change langly import in this file.

2023-10-02 07:51 UTC, EliasEriksson commented on src/State/Users.ts
> +			const users = this.#value
this.#value is narrowed in this scope from line 29 but will reset to its full type when used in functions. In this case the filter function.

2023-10-02 07:52 UTC, TheLillyleaf requested changes
Some minor things

2023-10-02 07:52 UTC, TheLillyleaf commented on src/components/user/list/index.tsx
> +				(this.users = (users || undefined)?.filter(user => this.organization?.users.includes(user.email) ?? true))
What does the `true` do here?

2023-10-02 07:52 UTC, TheLillyleaf commented on src/components/user/list/invite/translation/index.ts
> +import { sv } from "./sv"
imports

2023-10-02 07:52 UTC, TheLillyleaf commented on src/components/user/list/row/translation/index.ts
> +import { sv } from "./sv"
imports

2023-10-02 08:11 UTC, EliasEriksson commented on src/components/user/list/index.tsx
> +				(this.users = (users || undefined)?.filter(user => this.organization?.users.includes(user.email) ?? true))
it becomes the fallback value for `this.organization` if its undefined. the result end up being that if there is no organization to filter on it doesn't filter. it accepts all values in the array. This could be checked before the filter which would still leave typescript to think that `this.organization` can be undefined but would never be the case for us here. That would look like this if we prefer that:
```ts
this.state.users.listen("value", users => {             //  |
  this.users = !this.organization                       //  |
    ? users || undefined                                // \|/  Still have to be there
    : (users || undefined)?.filter(user => this.organization?.users.includes(user.email))
})
```

2023-10-02 08:16 UTC, TheLillyleaf approved these changes

2023-10-02 08:19 UTC, TheLillyleaf approved these changes

2023-10-02 08:20 UTC, merged