name files created
userwidgets/ui pull request #95
Opened 2023-10-04 07:17 UTC by linusarnejohansson

not ready yet.

2023-10-05 07:38 UTC, linusarnejohansson commented
the changes are tested to work with:
- changing name
- changing password

2023-10-06 07:51 UTC, linusarnejohansson commented
need the changes in https://github.com/userwidgets/model/pull/59 to work

2023-10-09 07:39 UTC, EliasEriksson requested changes
some fixes

2023-10-09 07:39 UTC, EliasEriksson commented on src/State/Users.ts
> +	async update( //this function requires more control and checks. More error messages. Also a success message if everything was successful.
remove comment

2023-10-09 07:39 UTC, EliasEriksson commented on src/State/Users.ts
> +		// this should reauthenticate the user by using the login function(?) but giving it the current token instead of the email and password as credentials
remvoe comment

2023-10-09 07:39 UTC, EliasEriksson commented on src/State/Users.ts
> +		console.log("state update", result, "this.state.me.key", this.state.me.key)
remove log

2023-10-09 07:39 UTC, EliasEriksson commented on src/State/Users.ts
> +	// }
this section can be removed

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +		//fix error message and flow, needs more checks(?)
remove

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +						disabled={!!this.request} //add check to disable if this.change.name == original name
remove comment

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +						First name
add translation

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +						Last name
add translation

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +			this.notice.emit(smoothly.Notice.failed("Malformed name."))
add translation

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +			this.notice.emit(smoothly.Notice.failed("need a token"))
add translation

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +			this.notice.emit(smoothly.Notice.failed("failed to update name"))
add translation

2023-10-09 07:39 UTC, EliasEriksson commented on src/components/me/name/index.tsx
> +			this.notice.emit(smoothly.Notice.succeeded("Your name has been updated"))
add translation

2023-10-09 08:51 UTC, EliasEriksson approved these changes

2023-10-09 08:53 UTC, merged