feat: Existing users permissions can be edited
userwidgets/ui pull request #99
Opened 2023-10-09 13:02 UTC by EliasEriksson

* existing users permissions can be edited
* new role state
  * roles are specified by the user of `userwidgets/ui` see how in demo
  * roles can be translated if desired
  * If no role is defined defaults are generated
* only refreshing token if change was made to self in users
* fetching the user list again if some user was updated

2023-10-09 13:08 UTC, EliasEriksson reviewed
self check

2023-10-09 14:50 UTC, linusarnejohansson requested changes

2023-10-09 14:50 UTC, linusarnejohansson commented on src/State/Roles/Role.ts
> +		return (({ label: display, ...role }) => ({
change name of display to label

2023-10-09 14:50 UTC, linusarnejohansson commented on src/components/user/translation/sv.ts
> +	"Failed to update user": "Mysklyckades med att updatera användaren",
mysklyckades -> misslyckades

2023-10-09 15:03 UTC, linusarnejohansson approved these changes

2023-10-10 06:53 UTC, linusarnejohansson approved these changes

2023-10-10 06:55 UTC, merged